### PR TITLE
Fixed typo in Physics.CollisionDetection:121

### PR DESCRIPTION
**Pull request by sortraev**
Max(exitTime.Y, exitTime.Y)   ->   Max(exitTime.X, exitTime.Y)

### CODE REVIEW

**Comment by Syrlander** [comment]
This is still an issue and leads to problems with the implementation of assignment 9. My group and I fixed it by changing the line to:
float exitTimeMin = System.Math.Min(exitTime.X, exitTime.Y);
This seemed to fix the problem for many other groups we've told, and it also passes the unittests.

(Many others working on the assignment might still encounter the issue, we only found it through relentless hours of debugging)

**Comment by alexpanter** [comment]
Great work! I will make some more unit tests, there has been problems with this algorithm.
It would be great though, if you could explain exactly, what issues you have been encountering.

I cannot accept the merge request until I understand what issues are being fixed. :)

**Comment by Syrlander** [comment]
The problem first occurred during our implementation of assignment 9, where we have a player entity which is capable of moving in an upward, left and right direction. Aside from just the player each level consists of a set of entities, or walls, the player can collide with and when this happens the game should end.

The problem is then that the player was colliding with the wall entities when it was far from them. Here we resulted to looking at the debugger and finding the specific entity the player was colliding with, to ensure that they in fact were far apart and shouldn't be colliding.

After debugging the return statements of the Aabb method we found line 121, which seemed rather odd since the line was finding the maximum of the same value and assigning it to a variable including "min". Through some minor code-and-fix, we found the solution as previously described, which also made much more sense in regards to the naming of the variable being assigned.

This problem has occurred with other groups working on assignment 9 and the fix seems to have fixed it for every group we've talked with. Furthermore the bug just seems like a typo, which was made during the implementation of Aabb.

**Comment by alexpanter** [comment]
Alright. I am now working on unit testing - so far no errors are showing up.

Could you develop a unit test that reproduces your error?
You can paste the code here. It would be very helpful.

**Comment by Syrlander** [comment]
I have successfully created a unit test where Aabb returns true when it should be false:

`[Test]
        public void TestAssignment9Error() {
            // Copied in the exact parameters from assignment 9 debug run where it first fails
            StationaryShape s = new StationaryShape(new Vec2F(0.9f, 0.739130437f), new Vec2F(0.025f, 0.0434782617f));
            DynamicShape a = new DynamicShape(new Vec2F(0.744843602f, 0.783036947f), 
                new Vec2F(0.065f, 0.05f), new Vec2F(-0.00157072174f, -0.00205000024f));
            
            Assert.AreEqual(false, CollisionDetection.Aabb(a, s).Collision);
        }`

The specific values have been gotten from the debugger of our assignment 9 implementation, when the first invalid collision happens. Here the stationary shape is the wall entity and the dynamic is the player.

**Comment by alexpanter** [comment]
Great! I am also developing some tests, I will put it together.

**Comment by alexpanter** [comment]
Thank you @Syrlander  (Simon Surland Andersen).
Your change has been pushed to the master branch.
I will also add your name to the list of contributors for DIKUArcade :)

**Pull request closed without merging**
